"""Relatório acadêmico. Dependência editorial opcional: reportlab (não exigida pela aplicação)."""
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
import argparse
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,default=ROOT/'document/Relatorio-Academico-CardioIA-Guilherme-Yamada-Dantas-RM568506.pdf');args=parser.parse_args();args.output.parent.mkdir(parents=True,exist_ok=True)
PINK=colors.HexColor('#ed145b');DARK=colors.HexColor('#202832');MUTED=colors.HexColor('#53606b');LIGHT=colors.HexColor('#f3f5f7')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodyAcademic',fontName='Times-Roman',fontSize=11.5,leading=16,alignment=TA_JUSTIFY,spaceAfter=10,textColor=DARK))
styles.add(ParagraphStyle(name='HAcademic',fontName='Helvetica-Bold',fontSize=14,leading=18,spaceBefore=12,spaceAfter=10,textColor=DARK))
styles.add(ParagraphStyle(name='SubAcademic',fontName='Helvetica-Bold',fontSize=11,leading=15,spaceBefore=9,spaceAfter=7,textColor=DARK))
styles.add(ParagraphStyle(name='SmallAcademic',fontName='Helvetica',fontSize=9,leading=12,spaceAfter=7,textColor=MUTED))
styles.add(ParagraphStyle(name='CenterAcademic',fontName='Helvetica',fontSize=11,leading=16,alignment=TA_CENTER,spaceAfter=10,textColor=DARK))
styles.add(ParagraphStyle(name='TitleAcademic',fontName='Helvetica-Bold',fontSize=27,leading=33,alignment=TA_CENTER,spaceAfter=13,textColor=DARK))
styles.add(ParagraphStyle(name='CellAcademic',fontName='Helvetica',fontSize=9,leading=12,textColor=DARK))
def P(s,style='BodyAcademic'):return Paragraph(s,styles[style])
def H(s):return P(s,'HAcademic')
def S(s):return P(s,'SubAcademic')
def table(rows,widths):
 t=Table([[P(str(v),'CellAcademic') for v in row] for row in rows],colWidths=widths,hAlign='LEFT')
 t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),LIGHT),('LINEBELOW',(0,0),(-1,0),1,PINK),('LINEBELOW',(0,1),(-1,-1),.35,colors.HexColor('#dce1e5')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8)]));return t
repo='https://github.com/japatraderdev99/cap2-robos-sinapses-medicina-guilherme-yamada-dantas'
portal='https://github.com/japatraderdev99/guilherme-yamada-dantas-cardioia-portal'
yts=['https://www.youtube.com/watch?v=KCmZu85N5qk','https://www.youtube.com/watch?v=ZsAI8kAWcYw','https://www.youtube.com/watch?v=1bPnMXL78pU']
def link(label,url):return P(f'<link href="{url}" color="#ac1045"><u>{label}</u></link>','SmallAcademic')
content=[]
content += [Spacer(1,12),Image(str(ROOT/'assets/logo-fiap.png'),width=176,height=47.4),Spacer(1,20),P('FACULDADE DE INFORMÁTICA E ADMINISTRAÇÃO PAULISTA','CenterAcademic'),P('Inteligência Artificial e Machine Learning<br/>Fase 2','CenterAcademic'),Spacer(1,25),P('CardioIA','TitleAcademic'),P('Diagnóstico Automatizado<br/>IA no Estetoscópio Digital','CenterAcademic'),Spacer(1,23),P('<b>Guilherme Yamada Dantas</b><br/>RM 568506','CenterAcademic'),Spacer(1,15),P('Relatório acadêmico de síntese do Desafio Integrador:<br/>IA entre Robôs, Sinapses e Medicina.','CenterAcademic'),Spacer(1,22),H('Resumo'),P('O projeto CardioIA apresenta uma solução acadêmica composta por extração de sintomas baseada em regras e classificação de textos sintéticos com TF-IDF e regressão logística. O núcleo utiliza dez relatos completos e uma base de 160 frases rotuladas. Como atividades complementares, foram desenvolvidos um portal responsivo em React e um experimento de classificação de imagens de eletrocardiogramas com rede neural MLP. O trabalho reúne código, dados, notebooks executados, testes, documentação e vídeos. Os resultados são interpretados em conjunto com os limites das amostras e não constituem validação clínica.'),P('<b>Palavras-chave:</b> processamento de linguagem natural; TF-IDF; classificação; React; eletrocardiograma; redes neurais.'),Spacer(1,12),P('7 de outubro de 2026','CenterAcademic'),PageBreak()]
content += [H('1. Introdução e objetivos'),P('A atividade propõe relacionar relatos de sintomas a hipóteses didáticas e treinar um classificador binário de risco textual. O objetivo foi implementar um fluxo reproduzível, com dados organizados e avaliação explícita, distinguindo regras de associação de padrões aprendidos por um modelo. Os desafios Ir Além ampliam a solução para uma interface web e para o processamento de imagens de ECG.'),H('2. Metodologia e implementação'),S('2.1 Núcleo obrigatório: extração e classificação'),P('Foram criados dez relatos fictícios com sintomas, referência temporal e impacto na rotina, além de um mapa CSV com quatro associações didáticas. O extrator em Python normaliza o texto, reconhece expressões e trata negação simples, contexto familiar, ausência de correspondência e contradições. As hipóteses são apresentadas com a regra acionada; não representam diagnóstico médico.'),P('A base de classificação contém 160 frases, equilibradas entre baixo risco e alto risco. Há 40 cenários com quatro paráfrases cada. A separação estratificada mantém cada cenário em apenas uma partição: 96 frases para treino, 32 para validação e 32 para teste. Um Pipeline ajusta o TF-IDF exclusivamente no treino e utiliza regressão logística. A avaliação inclui acurácia, baseline, matriz de confusão e análise de erros.'),S('2.2 Ir Além 1: portal React'),P('O portal usa React e Vite, Context API, JWT fictício no localStorage, rotas protegidas, pacientes simulados e agendamento com gerenciamento de estado. Inclui painel de métricas, persistência local, validação de conflitos e CSS Modules. A autenticação é uma simulação de interface, sem servidor de segurança e sem dados clínicos reais.'),S('2.3 Ir Além 2: imagens de ECG e MLP'),P('O experimento reutiliza 120 imagens de 119 pacientes da base pública PTB-XL 1.0.3, obtidas na Fase 1. A classe NORM é agrupada como normal; CD, HYP, MI e STTC como anormal. Esse agrupamento representa superclasses diagnósticas, e não apenas arritmias. O cabeçalho com diagnóstico é removido antes da conversão para cinza e do redimensionamento para 264 × 136 pixels.'),P('Os pixels normalizados formam vetores de 35.904 valores. A MLP em Keras utiliza camadas densas de 32 e 16 unidades, ReLU, regularização L2, Dropout e saída sigmoide. Treino, validação e teste são separados por paciente, com 72, 24 e 24 exames. O treinamento usa pesos de classe e early stopping pela perda de validação: 15 épocas executadas e melhor época 7. O limiar foi fixado em 0,5.'),PageBreak()]
content += [H('3. Resultados e análise crítica'),table([['Experimento / conjunto','Resultado','Interpretação'],['Texto - treino / validação / teste','100% / 75% / 100%','Acurácia em base sintética; baseline de teste: 50%.'],['ECG - teste reservado','79,17%','Igual ao baseline majoritário; 24 exames de teste.'],['ECG - acurácia balanceada','50%','Todos os exames previstos como anormais.'],['Verificação de software','33 + 7 testes','33 testes Python e 7 testes do portal aprovados.']],[177,103,195]),Spacer(1,14),S('3.1 Interpretação do classificador de texto'),P('O teste textual inclui oito cenários independentes e 32 frases. A acurácia de 100% deve ser lida com cautela: os exemplos são sintéticos, pequenos e produzidos pelo mesmo processo de elaboração. A validação de 75% mostra variação entre as partições. Sondagens posteriores identificaram falha com negação: o classificador pode atribuir alto risco tanto a uma afirmação quanto à sua forma negada. A limitação está documentada e não foi ocultada pela métrica agregada.'),S('3.2 Interpretação da rede neural de ECG'),P('A rede acertou os 19 casos anormais e classificou incorretamente os cinco casos normais como anormais. O recall da classe normal foi 0%, e o da classe anormal, 100%. Portanto, a acurácia de 79,17% não demonstra ganho sobre a estratégia de sempre prever a classe majoritária. A amostra é pequena e o redimensionamento reduz detalhes do sinal. Os resultados não comprovam utilidade clínica.'),S('3.3 Qualidade, reprodutibilidade e governança'),P('O projeto preserva a origem dos dados, registra métricas e partições e inclui notebooks com saídas de execução. Os testes e as rotinas de validação automatizada estão versionados; o portal também passou por build e conferência de formatação. Os repositórios adotam a organização do template FIAP e identificam o autor e o RM. O ECG possui licença e manifesto de arquivos; textos e pacientes do portal são fictícios.'),H('4. Conclusão'),P('Os componentes solicitados foram implementados e documentados, permitindo estudar extração de informações, aprendizado supervisionado, interfaces e redes neurais. A principal contribuição acadêmica é a execução verificável acompanhada de análise crítica: bom resultado em corpus sintético não implica generalização, e acurácia isolada pode ocultar um classificador sem discriminação útil. Uma evolução futura exigiria dados mais diversos e avaliação externa, com protocolo definido antes do teste.'),PageBreak()]
content += [H('5. Acesso ao código e às demonstrações'),P('Os links abaixo são clicáveis. Os repositórios são públicos e contêm instruções de instalação e execução. Os três vídeos exibem o selo “Não listado”; títulos, reprodução e durações foram conferidos no YouTube em 7 de outubro de 2026.'),S('5.1 Repositórios GitHub'),link('Projeto principal: NLP obrigatório e extra ECG',repo),P(repo,'SmallAcademic'),link('Portal React: pacientes, consultas e painel',portal),P(portal,'SmallAcademic'),S('5.2 Vídeos no YouTube'),table([['Parte','Duração exibida'],['Vídeo 1 - NLP: extração e classificação','2min24s'],['Vídeo 2 - Portal de pacientes e consultas','2min39s'],['Vídeo 3 - ECG e rede neural MLP','3min15s']],[362,113]),Spacer(1,10)]
for i,u in enumerate(yts,1):content.append(link(f'Vídeo {i}: {u}',u))
content += [S('5.3 Arquivos que acompanham o relatório'),P('O pacote principal reúne relatos TXT, mapa e base CSV, código Python, notebooks, evidências e o extra ECG. O pacote do portal reúne código React, dependências declaradas, testes e documentação. Os nomes dos arquivos ZIP são:'),P('CardioIA-Fase2-Guilherme-Yamada-Dantas-RM568506.zip<br/>CardioIA-Portal-Guilherme-Yamada-Dantas-RM568506.zip','SmallAcademic'),P('Este relatório é uma síntese complementar. Não substitui os arquivos executáveis, os repositórios ou a submissão na plataforma. Não há exigência explícita de relatório PDF no enunciado consultado.','SmallAcademic'),H('Referências'),link('FIAP. Desafio Integrador: IA entre Robôs, Sinapses e Medicina. Fase 2, 2026.','https://on.fiap.com.br/mod/assign/view.php?id=656852&returnto=conteudocurso'),link('FIAP. Template de organização do projeto. Commit 50e1e272, consultado em 07/10/2026.','https://github.com/agodoi/templateFiapVfinal'),link('PHYSIONET. PTB-XL, a large publicly available electrocardiography dataset. Versão 1.0.3.','https://physionet.org/content/ptb-xl/1.0.3/'),link('SCIKIT-LEARN. Common pitfalls and recommended practices: prevenção de vazamento.','https://scikit-learn.org/stable/common_pitfalls.html'),P('Fontes dos resultados: arquivos de métricas, notebooks e documentação versionados nos repositórios indicados. Logo obtido do template FIAP; atribuição CC BY 4.0 preservada.','SmallAcademic')]
def footer(canvas,doc):
 canvas.saveState();w,h=A4
 if doc.page>1:
  canvas.setFont('Helvetica',8);canvas.setFillColor(MUTED);canvas.drawString(60,h-34,'FIAP | CARDIOIA | RELATÓRIO ACADÊMICO');canvas.setStrokeColor(PINK);canvas.line(60,h-42,w-60,h-42)
 canvas.setStrokeColor(colors.HexColor('#dce1e5'));canvas.line(60,44,w-60,44)
 canvas.setFont('Helvetica',8);canvas.setFillColor(MUTED);canvas.drawString(60,30,'Guilherme Yamada Dantas | RM 568506');canvas.drawRightString(w-60,30,str(doc.page));canvas.restoreState()
doc=SimpleDocTemplate(str(args.output),pagesize=A4,rightMargin=60,leftMargin=60,topMargin=59,bottomMargin=60,title='CardioIA - Relatório acadêmico da Fase 2',author='Guilherme Yamada Dantas - RM 568506',subject='NLP, portal React e rede neural MLP de ECG')
doc.build(content,onFirstPage=footer,onLaterPages=footer)
print(args.output)
