[theme]
primaryColor = "#176C78"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EDF4F6"
textColor = "#183347"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"

